### ISSUE TITLE
Getting 404 Error for every request (Apache)

### ISSUE THREAD

**Issue by DrewThomasCorps** [slimphp/Slim-Skeleton#131] opened 2019-09-26 13:41 UTC
My document root was MAMP/htdocs and my index.php was in htdocs/project-name/public/

Going to http://localhost:8888/project-name/public/users returned a 404 error.

My routes were going through the index.php, but were always returning a 404 code. I eventually fixed it by adding the following htaccess file to my project's root directory.

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ public/index.php [QSA,L]

Then http://localhost8888/project-name/users worked

**Comment by Xcreen** [comment] 2019-09-27 15:06
It makes more sense to create a vhost with document-root to your public-dir. 
Otherwise you need to adjust your htaccess when you application goes live on producation server (with real domain).

**Comment by ThisIsVegas** [comment] 2019-12-18 06:27
I'd like to share [this solution](https://github.com/slimphp/Slim/issues/2512#issuecomment-486161481) that works for me by using the `selective/basepath` package to resolving directory issue.

**Comment by esteindavila** [comment] 2019-12-22 04:14
hola buenas noches alguien me puede ayudar en este error, me sale después de haber instalado slim-skeleton

{
    "statusCode": 404,
    "error": {
        "type": "RESOURCE_NOT_FOUND",
        "description": "Not found."
    }
}

**Comment by kwhat** [comment] 2020-01-22 19:24
This is still a pain using nginx as well.  I  am not sure what basePath is for, but its not working for route matching.  Is this feature only used for redirection / route resolution and not route matching?  I mean you set this on the route collector, and it looks like the Dispatcher is using it, so I would guess it should be used as part of the route matching process, but it keeps returning a 404 unless the basepath is stripped from the request by the webserver.  Is this the intended behavior in Slim4?  I seem to remember this working _correctly_ in Slim 3.

**Comment by l0gicgate** [comment] 2020-05-07 14:43
I’m closing this as no further feedback has been provided.

**Closed by l0gicgate** 2020-05-07 14:43 UTC
