### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim-Skeleton#43] opened 2016-08-30 08:42 UTC
I think test are not working because there is no "require __DIR__ . '/../../vendor/autoload.php';" in HomepageTest.php file

**Comment by casmith** [comment] 2016-09-02 14:34
This is biting me as well on ubuntu running php7. If I create a fresh project using slim/slim-skeleton and run vendor/bin/phpunit, I get the following error: 

PHP Fatal error:  Class 'Tests\Functional\BaseTestCase' not found in /home/casmith/work/slim-skel3/tests/functional/HomepageTest.php on line 5

**Comment by maccath** [comment] 2016-09-02 14:53
If you check the `phpunit.xml` configuration, you can see that there is a `bootstrap` parameter on `<phpunit>`. This should point to the `vendor/autoload.php` file, which @casmith correctly identified as potentially being the missing link.

That it is not being loaded in through the config may be an OS-specific error, as I can't reproduce it. Could you try changing the `bootstrap` param in `phpunit.xml` to `./vendor/autoload.php` instead and let me know if this solves the issue? If so, I will submit a fix for this.

**Comment by casmith** [comment] 2016-09-02 16:26
I tried modifying the bootstrap attribute in phpunit.xml as described and it had no effect. I had also tried using require_once to load the autoloader in HomepageTest.php as well, and it was still not finding the BaseTestCase class. I had to manually require BaseTestCase from within HomepageTest to get it working. It seems the autoloader is not always correctly requiring the base class on linux. Could it have something to do with the filesystem being case sensitive?

**Comment by akrabat** [comment] 2016-09-04 09:17
> Could it have something to do with the filesystem being case sensitive?

I suspect that you're right. The `functional` directory should be `Functional`.

**Closed** 2016-09-04 13:16 UTC

**Comment by piernik** [comment] 2016-09-05 08:39
It's still not working for me. Have to add my own require

**Comment by maccath** [comment] 2016-09-05 08:42
@piernik - can you check manually and verify that the tests/Functional directory has an uppercase F? I've had an issue before where Git doesn't register case changes as actual changes. You may need to manually update it.

**Comment by akrabat** [comment] 2016-09-05 08:43
Also, this change only affects new projects. Any existing projects will need to be manually changed.

**Comment by kevinburke** [comment] 2016-11-22 22:29
I'm still running into this issue; I just installed the project today.

```
./vendor/bin/phpunit --bootstrap='vendor/autoload.php' tests/Functional
PHP Fatal error:  Class 'Tests\Functional\BaseTestCase' not found in /Users/kevin/code/project/web/tests/Functional/HomepageTest.php on line 5

Fatal error: Class 'Tests\Functional\BaseTestCase' not found in /Users/kevin/code/project/web/tests/Functional/HomepageTest.php on line 5
```

I'm not sure what I'm missing. I'm definitely loading the bootstrap file, since if I change the filename, phpunit provides a different error.

**Comment by kevinburke** [comment] 2016-11-22 22:32
Never mind, I needed to add `autoload-dev`.
